name: linklab_flutter_sdk
description: Flutter SDK for LinkLab deep linking service
version: 0.1.4
homepage: https://linklab.cc

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: cc.linklab.flutter
        pluginClass: LinkLabFlutterPlugin
      ios:
        pluginClass: LinkLabFlutterPlugin